# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kodosBA.ui'
#
# Created: Wed Jan 13 21:16:48 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_KodosBA(object):
    def setupUi(self, KodosBA):
        KodosBA.setObjectName("KodosBA")
        KodosBA.resize(590, 900)
        self.widget = QtGui.QWidget(KodosBA)
        self.widget.setObjectName("widget")
        self.gridlayout = QtGui.QGridLayout(self.widget)
        self.gridlayout.setObjectName("gridlayout")
        self.groupBox1 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName("groupBox1")
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox1)
        self.gridlayout1.setObjectName("gridlayout1")
        self.regexMultiLineEdit = QtGui.QPlainTextEdit(self.groupBox1)
        self.regexMultiLineEdit.setObjectName("regexMultiLineEdit")
        self.gridlayout1.addWidget(self.regexMultiLineEdit, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.resultTabWidget = QtGui.QTabWidget(self.widget)
        self.resultTabWidget.setObjectName("resultTabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout2 = QtGui.QGridLayout(self.tab)
        self.gridlayout2.setObjectName("gridlayout2")
        self.groupTable = QtGui.QTableWidget(self.tab)
        self.groupTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.groupTable.setObjectName("groupTable")
        self.groupTable.setColumnCount(2)
        self.groupTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.groupTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.groupTable.setHorizontalHeaderItem(1, item)
        self.gridlayout2.addWidget(self.groupTable, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.tab, "")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridlayout3 = QtGui.QGridLayout(self.tab1)
        self.gridlayout3.setObjectName("gridlayout3")
        self.matchTextBrowser = QtGui.QTextBrowser(self.tab1)
        self.matchTextBrowser.setObjectName("matchTextBrowser")
        self.gridlayout3.addWidget(self.matchTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.tab1, "")
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName("TabPage")
        self.gridlayout4 = QtGui.QGridLayout(self.TabPage)
        self.gridlayout4.setObjectName("gridlayout4")
        self.matchAllTextBrowser = QtGui.QTextBrowser(self.TabPage)
        self.matchAllTextBrowser.setObjectName("matchAllTextBrowser")
        self.gridlayout4.addWidget(self.matchAllTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage, "")
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName("TabPage1")
        self.vboxlayout = QtGui.QVBoxLayout(self.TabPage1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.replaceTextBrowser = QtGui.QTextBrowser(self.TabPage1)
        self.replaceTextBrowser.setObjectName("replaceTextBrowser")
        self.vboxlayout.addWidget(self.replaceTextBrowser)
        self.resultTabWidget.addTab(self.TabPage1, "")
        self.TabPage2 = QtGui.QWidget()
        self.TabPage2.setObjectName("TabPage2")
        self.gridlayout5 = QtGui.QGridLayout(self.TabPage2)
        self.gridlayout5.setObjectName("gridlayout5")
        self.codeTextBrowser = QtGui.QTextBrowser(self.TabPage2)
        self.codeTextBrowser.setObjectName("codeTextBrowser")
        self.gridlayout5.addWidget(self.codeTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage2, "")
        self.gridlayout.addWidget(self.resultTabWidget, 5, 0, 1, 1)
        self.tabWidget3 = QtGui.QTabWidget(self.widget)
        self.tabWidget3.setObjectName("tabWidget3")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridlayout6 = QtGui.QGridLayout(self.tab2)
        self.gridlayout6.setObjectName("gridlayout6")
        self.stringMultiLineEdit = QtGui.QPlainTextEdit(self.tab2)
        self.stringMultiLineEdit.setObjectName("stringMultiLineEdit")
        self.gridlayout6.addWidget(self.stringMultiLineEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab2, "")
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridlayout7 = QtGui.QGridLayout(self.tab3)
        self.gridlayout7.setObjectName("gridlayout7")
        self.replaceTextEdit = QtGui.QTextEdit(self.tab3)
        self.replaceTextEdit.setObjectName("replaceTextEdit")
        self.gridlayout7.addWidget(self.replaceTextEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab3, "")
        self.gridlayout.addWidget(self.tabWidget3, 3, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(70, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.textLabel1 = QtGui.QLabel(self.widget)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.hboxlayout.addWidget(self.textLabel1)
        self.matchNumberSpinBox = QtGui.QSpinBox(self.widget)
        self.matchNumberSpinBox.setMinimum(1)
        self.matchNumberSpinBox.setMaximum(9999)
        self.matchNumberSpinBox.setObjectName("matchNumberSpinBox")
        self.hboxlayout.addWidget(self.matchNumberSpinBox)
        self.spacerLabel = QtGui.QLabel(self.widget)
        self.spacerLabel.setPixmap(QtGui.QPixmap("image1"))
        self.spacerLabel.setWordWrap(False)
        self.spacerLabel.setObjectName("spacerLabel")
        self.hboxlayout.addWidget(self.spacerLabel)
        self.replaceLabel = QtGui.QLabel(self.widget)
        self.replaceLabel.setWordWrap(False)
        self.replaceLabel.setObjectName("replaceLabel")
        self.hboxlayout.addWidget(self.replaceLabel)
        self.replaceNumberSpinBox = QtGui.QSpinBox(self.widget)
        self.replaceNumberSpinBox.setObjectName("replaceNumberSpinBox")
        self.hboxlayout.addWidget(self.replaceNumberSpinBox)
        spacerItem1 = QtGui.QSpacerItem(118, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridlayout.addLayout(self.hboxlayout, 4, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ignorecaseCheckBox = QtGui.QCheckBox(self.groupBox)
        self.ignorecaseCheckBox.setObjectName("ignorecaseCheckBox")
        self.horizontalLayout.addWidget(self.ignorecaseCheckBox)
        self.multilineCheckBox = QtGui.QCheckBox(self.groupBox)
        self.multilineCheckBox.setObjectName("multilineCheckBox")
        self.horizontalLayout.addWidget(self.multilineCheckBox)
        self.dotallCheckBox = QtGui.QCheckBox(self.groupBox)
        self.dotallCheckBox.setObjectName("dotallCheckBox")
        self.horizontalLayout.addWidget(self.dotallCheckBox)
        self.verboseCheckBox = QtGui.QCheckBox(self.groupBox)
        self.verboseCheckBox.setObjectName("verboseCheckBox")
        self.horizontalLayout.addWidget(self.verboseCheckBox)
        self.localeCheckBox = QtGui.QCheckBox(self.groupBox)
        self.localeCheckBox.setObjectName("localeCheckBox")
        self.horizontalLayout.addWidget(self.localeCheckBox)
        self.unicodeCheckBox = QtGui.QCheckBox(self.groupBox)
        self.unicodeCheckBox.setObjectName("unicodeCheckBox")
        self.horizontalLayout.addWidget(self.unicodeCheckBox)
        self.gridlayout.addWidget(self.groupBox, 1, 0, 1, 1)
        KodosBA.setCentralWidget(self.widget)
        self.toolBar = QtGui.QToolBar(KodosBA)
        self.toolBar.setProperty("label", QtCore.QVariant(QtGui.QApplication.translate("KodosBA", "Tools", None, QtGui.QApplication.UnicodeUTF8)))
        self.toolBar.setObjectName("toolBar")
        KodosBA.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(KodosBA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 24))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setObjectName("editMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        KodosBA.setMenuBar(self.menubar)
        self.fileNewAction = QtGui.QAction(KodosBA)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image2"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileNewAction.setIcon(icon)
        self.fileNewAction.setProperty("name", QtCore.QVariant("fileNewAction"))
        self.fileNewAction.setObjectName("fileNewAction")
        self.fileOpenAction = QtGui.QAction(KodosBA)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image3"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon1)
        self.fileOpenAction.setProperty("name", QtCore.QVariant("fileOpenAction"))
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileSaveAction = QtGui.QAction(KodosBA)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image4"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSaveAction.setIcon(icon2)
        self.fileSaveAction.setProperty("name", QtCore.QVariant("fileSaveAction"))
        self.fileSaveAction.setObjectName("fileSaveAction")
        self.fileSaveAsAction = QtGui.QAction(KodosBA)
        self.fileSaveAsAction.setProperty("name", QtCore.QVariant("fileSaveAsAction"))
        self.fileSaveAsAction.setObjectName("fileSaveAsAction")
        self.fileExitAction = QtGui.QAction(KodosBA)
        self.fileExitAction.setProperty("name", QtCore.QVariant("fileExitAction"))
        self.fileExitAction.setObjectName("fileExitAction")
        self.editUndoAction = QtGui.QAction(KodosBA)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image5"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndoAction.setIcon(icon3)
        self.editUndoAction.setProperty("name", QtCore.QVariant("editUndoAction"))
        self.editUndoAction.setObjectName("editUndoAction")
        self.editRedoAction = QtGui.QAction(KodosBA)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image6"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRedoAction.setIcon(icon4)
        self.editRedoAction.setProperty("name", QtCore.QVariant("editRedoAction"))
        self.editRedoAction.setObjectName("editRedoAction")
        self.editCutAction = QtGui.QAction(KodosBA)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image7"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon5)
        self.editCutAction.setProperty("name", QtCore.QVariant("editCutAction"))
        self.editCutAction.setObjectName("editCutAction")
        self.editCopyAction = QtGui.QAction(KodosBA)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image8"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCopyAction.setIcon(icon6)
        self.editCopyAction.setProperty("name", QtCore.QVariant("editCopyAction"))
        self.editCopyAction.setObjectName("editCopyAction")
        self.editPasteAction = QtGui.QAction(KodosBA)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("image9"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPasteAction.setIcon(icon7)
        self.editPasteAction.setProperty("name", QtCore.QVariant("editPasteAction"))
        self.editPasteAction.setObjectName("editPasteAction")
        self.examineAction = QtGui.QAction(KodosBA)
        self.examineAction.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("image10"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.examineAction.setIcon(icon8)
        self.examineAction.setProperty("name", QtCore.QVariant("examineAction"))
        self.examineAction.setObjectName("examineAction")
        self.helpContentsAction = QtGui.QAction(KodosBA)
        self.helpContentsAction.setProperty("name", QtCore.QVariant("helpContentsAction"))
        self.helpContentsAction.setObjectName("helpContentsAction")
        self.helpIndexAction = QtGui.QAction(KodosBA)
        self.helpIndexAction.setProperty("name", QtCore.QVariant("helpIndexAction"))
        self.helpIndexAction.setObjectName("helpIndexAction")
        self.helpAboutAction = QtGui.QAction(KodosBA)
        self.helpAboutAction.setProperty("name", QtCore.QVariant("helpAboutAction"))
        self.helpAboutAction.setObjectName("helpAboutAction")
        self.regexChangedAction = QtGui.QAction(KodosBA)
        self.regexChangedAction.setProperty("name", QtCore.QVariant("regexChangedAction"))
        self.regexChangedAction.setObjectName("regexChangedAction")
        self.editPauseAction = QtGui.QAction(KodosBA)
        self.editPauseAction.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("image11"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPauseAction.setIcon(icon9)
        self.editPauseAction.setProperty("name", QtCore.QVariant("editPauseAction"))
        self.editPauseAction.setObjectName("editPauseAction")
        self.editPreferencesAction = QtGui.QAction(KodosBA)
        self.editPreferencesAction.setProperty("name", QtCore.QVariant("editPreferencesAction"))
        self.editPreferencesAction.setObjectName("editPreferencesAction")
        self.helpHelpAction = QtGui.QAction(KodosBA)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("image12"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpHelpAction.setIcon(icon10)
        self.helpHelpAction.setProperty("name", QtCore.QVariant("helpHelpAction"))
        self.helpHelpAction.setObjectName("helpHelpAction")
        self.helpPythonHelpAction = QtGui.QAction(KodosBA)
        self.helpPythonHelpAction.setProperty("name", QtCore.QVariant("helpPythonHelpAction"))
        self.helpPythonHelpAction.setObjectName("helpPythonHelpAction")
        self.helpRegexReferenceAction = QtGui.QAction(KodosBA)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("image13"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpRegexReferenceAction.setIcon(icon11)
        self.helpRegexReferenceAction.setProperty("name", QtCore.QVariant("helpRegexReferenceAction"))
        self.helpRegexReferenceAction.setObjectName("helpRegexReferenceAction")
        self.helpVisitWebsiteAction = QtGui.QAction(KodosBA)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("image14"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpVisitWebsiteAction.setIcon(icon12)
        self.helpVisitWebsiteAction.setProperty("name", QtCore.QVariant("helpVisitWebsiteAction"))
        self.helpVisitWebsiteAction.setObjectName("helpVisitWebsiteAction")
        self.helpCheckForUpdateAction = QtGui.QAction(KodosBA)
        self.helpCheckForUpdateAction.setProperty("name", QtCore.QVariant("helpCheckForUpdateAction"))
        self.helpCheckForUpdateAction.setObjectName("helpCheckForUpdateAction")
        self.helpReportBugAction = QtGui.QAction(KodosBA)
        self.helpReportBugAction.setProperty("name", QtCore.QVariant("helpReportBugAction"))
        self.helpReportBugAction.setObjectName("helpReportBugAction")
        self.noopAction = QtGui.QAction(KodosBA)
        self.noopAction.setEnabled(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("image15"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noopAction.setIcon(icon13)
        self.noopAction.setProperty("name", QtCore.QVariant("noopAction"))
        self.noopAction.setObjectName("noopAction")
        self.fileImportFileAction = QtGui.QAction(KodosBA)
        self.fileImportFileAction.setProperty("name", QtCore.QVariant("fileImportFileAction"))
        self.fileImportFileAction.setObjectName("fileImportFileAction")
        self.fileImportURLAction = QtGui.QAction(KodosBA)
        self.fileImportURLAction.setProperty("name", QtCore.QVariant("fileImportURLAction"))
        self.fileImportURLAction.setObjectName("fileImportURLAction")
        self.helpRegexLibAction = QtGui.QAction(KodosBA)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("image16"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpRegexLibAction.setIcon(icon14)
        self.helpRegexLibAction.setProperty("name", QtCore.QVariant("helpRegexLibAction"))
        self.helpRegexLibAction.setObjectName("helpRegexLibAction")
        self.FileRevertAction = QtGui.QAction(KodosBA)
        self.FileRevertAction.setProperty("name", QtCore.QVariant("FileRevertAction"))
        self.FileRevertAction.setObjectName("FileRevertAction")
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileSaveAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editCutAction)
        self.toolBar.addAction(self.editCopyAction)
        self.toolBar.addAction(self.editPasteAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editPauseAction)
        self.toolBar.addAction(self.examineAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.helpRegexReferenceAction)
        self.toolBar.addAction(self.helpRegexLibAction)
        self.fileMenu.addAction(self.fileNewAction)
        self.fileMenu.addAction(self.fileOpenAction)
        self.fileMenu.addAction(self.fileSaveAction)
        self.fileMenu.addAction(self.fileSaveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.FileRevertAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileImportFileAction)
        self.fileMenu.addAction(self.fileImportURLAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.fileMenu.addSeparator()
        self.editMenu.addAction(self.editUndoAction)
        self.editMenu.addAction(self.editRedoAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editCutAction)
        self.editMenu.addAction(self.editCopyAction)
        self.editMenu.addAction(self.editPasteAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.examineAction)
        self.editMenu.addAction(self.editPauseAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editPreferencesAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpHelpAction)
        self.helpMenu.addAction(self.helpPythonHelpAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpRegexReferenceAction)
        self.helpMenu.addAction(self.helpRegexLibAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpVisitWebsiteAction)
        self.helpMenu.addAction(self.helpCheckForUpdateAction)
        self.helpMenu.addAction(self.helpReportBugAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpAboutAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(KodosBA)
        self.resultTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dotallCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.editCopyAction, QtCore.SIGNAL("activated()"), KodosBA.editCopy)
        QtCore.QObject.connect(self.editCutAction, QtCore.SIGNAL("activated()"), KodosBA.editCut)
        QtCore.QObject.connect(self.editPasteAction, QtCore.SIGNAL("activated()"), KodosBA.editPaste)
        QtCore.QObject.connect(self.editRedoAction, QtCore.SIGNAL("activated()"), KodosBA.editRedo)
        QtCore.QObject.connect(self.editUndoAction, QtCore.SIGNAL("activated()"), KodosBA.editUndo)
        QtCore.QObject.connect(self.examineAction, QtCore.SIGNAL("activated()"), KodosBA.examine)
        QtCore.QObject.connect(self.fileExitAction, QtCore.SIGNAL("activated()"), KodosBA.close)
        QtCore.QObject.connect(self.fileNewAction, QtCore.SIGNAL("activated()"), KodosBA.fileNew)
        QtCore.QObject.connect(self.fileOpenAction, QtCore.SIGNAL("activated()"), KodosBA.fileOpen)
        QtCore.QObject.connect(self.fileSaveAction, QtCore.SIGNAL("activated()"), KodosBA.fileSave)
        QtCore.QObject.connect(self.fileSaveAsAction, QtCore.SIGNAL("activated()"), KodosBA.fileSaveAs)
        QtCore.QObject.connect(self.helpAboutAction, QtCore.SIGNAL("activated()"), KodosBA.helpAbout)
        QtCore.QObject.connect(self.helpContentsAction, QtCore.SIGNAL("activated()"), KodosBA.helpContents)
        QtCore.QObject.connect(self.helpHelpAction, QtCore.SIGNAL("activated()"), KodosBA.helpHelp)
        QtCore.QObject.connect(self.helpIndexAction, QtCore.SIGNAL("activated()"), KodosBA.helpIndex)
        QtCore.QObject.connect(self.ignorecaseCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.localeCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.matchNumberSpinBox, QtCore.SIGNAL("valueChanged(int)"), KodosBA.match_num_slot)
        QtCore.QObject.connect(self.multilineCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.unicodeCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.verboseCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.editPauseAction, QtCore.SIGNAL("toggled(bool)"), KodosBA.pause)
        QtCore.QObject.connect(self.editPreferencesAction, QtCore.SIGNAL("activated()"), KodosBA.preferences)
        QtCore.QObject.connect(self.helpReportBugAction, QtCore.SIGNAL("activated()"), KodosBA.report_bug)
        QtCore.QObject.connect(self.helpPythonHelpAction, QtCore.SIGNAL("activated()"), KodosBA.helpPythonRegex)
        QtCore.QObject.connect(self.helpRegexReferenceAction, QtCore.SIGNAL("activated()"), KodosBA.reference_guide)
        QtCore.QObject.connect(self.helpVisitWebsiteAction, QtCore.SIGNAL("activated()"), KodosBA.kodos_website)
        QtCore.QObject.connect(self.helpCheckForUpdateAction, QtCore.SIGNAL("activated()"), KodosBA.check_for_update)
        QtCore.QObject.connect(self.replaceTextEdit, QtCore.SIGNAL("textChanged()"), KodosBA.replace_changed_slot)
        QtCore.QObject.connect(self.replaceNumberSpinBox, QtCore.SIGNAL("valueChanged(int)"), KodosBA.replace_num_slot)
        QtCore.QObject.connect(self.fileImportFileAction, QtCore.SIGNAL("activated()"), KodosBA.importFile)
        QtCore.QObject.connect(self.fileImportURLAction, QtCore.SIGNAL("activated()"), KodosBA.importURL)
        QtCore.QObject.connect(self.helpRegexLibAction, QtCore.SIGNAL("activated()"), KodosBA.helpRegexLib)
        QtCore.QObject.connect(self.ignorecaseCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.replaceTextEdit, QtCore.SIGNAL("textChanged()"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.multilineCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.dotallCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.verboseCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.localeCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.unicodeCheckBox, QtCore.SIGNAL("toggled(bool)"), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.FileRevertAction, QtCore.SIGNAL("activated()"), KodosBA.revert_file_slot)
        QtCore.QObject.connect(self.regexMultiLineEdit, QtCore.SIGNAL("textChanged()"), KodosBA.regex_changed_slot)
        QtCore.QObject.connect(self.stringMultiLineEdit, QtCore.SIGNAL("textChanged()"), KodosBA.string_changed_slot)
        QtCore.QMetaObject.connectSlotsByName(KodosBA)
        KodosBA.setTabOrder(self.regexMultiLineEdit, self.stringMultiLineEdit)
        KodosBA.setTabOrder(self.stringMultiLineEdit, self.resultTabWidget)
        KodosBA.setTabOrder(self.resultTabWidget, self.matchNumberSpinBox)
        KodosBA.setTabOrder(self.matchNumberSpinBox, self.matchTextBrowser)
        KodosBA.setTabOrder(self.matchTextBrowser, self.codeTextBrowser)

    def retranslateUi(self, KodosBA):
        KodosBA.setWindowTitle(QtGui.QApplication.translate("KodosBA", "Kodos - The Python Regex Debugger", None, QtGui.QApplication.UnicodeUTF8))
        KodosBA.setWindowIconText(QtGui.QApplication.translate("KodosBA", "Kodos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("KodosBA", "Regular Expression Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("KodosBA", "Group Name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("KodosBA", "Match", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab), QtGui.QApplication.translate("KodosBA", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab1), QtGui.QApplication.translate("KodosBA", "Match", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage), QtGui.QApplication.translate("KodosBA", "Match All", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage1), QtGui.QApplication.translate("KodosBA", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage2), QtGui.QApplication.translate("KodosBA", "Sample Code", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab2), QtGui.QApplication.translate("KodosBA", "Search String", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab3), QtGui.QApplication.translate("KodosBA", "Replace String", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("KodosBA", "Match Number", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceLabel.setText(QtGui.QApplication.translate("KodosBA", "Replace Number", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("KodosBA", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorecaseCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "Perform case-insensitive matching; expressions like [A-Z] will match\n"
"lowercase letters, too. This is not affected by the current locale.", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorecaseCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.multilineCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "When specified, the pattern character \"^\" matches at the beginning of the \n"
"string and at the beginning of each line (immediately following each newline); \n"
"and the pattern character \"$\" matches at the end of the string and at the end \n"
"of each line (immediately preceding each newline). By default, \"^\" matches \n"
"only at the beginning of the string, and \"$\" only at the end of the string and \n"
"immediately before the newline (if any) at the end of the string.", None, QtGui.QApplication.UnicodeUTF8))
        self.multilineCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Multi Line", None, QtGui.QApplication.UnicodeUTF8))
        self.dotallCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "Make the \".\" special character match any character at all, including a \n"
"newline; without this flag, \".\" will match anything except a newline.", None, QtGui.QApplication.UnicodeUTF8))
        self.dotallCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Dot All", None, QtGui.QApplication.UnicodeUTF8))
        self.verboseCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "This flag allows you to write regular expressions that look nicer. Whitespace \n"
"within the pattern is ignored, except when in a character class or preceded by \n"
"an unescaped backslash, and, when a line contains a \"#\" neither in a character\n"
"class or preceded by an unescaped backslash, all characters from the leftmost \n"
"such \"#\" through the end of the line are ignored.", None, QtGui.QApplication.UnicodeUTF8))
        self.verboseCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.localeCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "Make \\w, \\W, \\b, and \\B dependent on the current locale.", None, QtGui.QApplication.UnicodeUTF8))
        self.localeCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Locale", None, QtGui.QApplication.UnicodeUTF8))
        self.unicodeCheckBox.setToolTip(QtGui.QApplication.translate("KodosBA", "\"Make \\w, \\W, \\b, and \\B dependent on the Unicode character properties \n"
"database. New in Python version 2.0.", None, QtGui.QApplication.UnicodeUTF8))
        self.unicodeCheckBox.setText(QtGui.QApplication.translate("KodosBA", "Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("KodosBA", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("KodosBA", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("KodosBA", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setText(QtGui.QApplication.translate("KodosBA", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setIconText(QtGui.QApplication.translate("KodosBA", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("KodosBA", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setIconText(QtGui.QApplication.translate("KodosBA", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setText(QtGui.QApplication.translate("KodosBA", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setIconText(QtGui.QApplication.translate("KodosBA", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setText(QtGui.QApplication.translate("KodosBA", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setIconText(QtGui.QApplication.translate("KodosBA", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setText(QtGui.QApplication.translate("KodosBA", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setIconText(QtGui.QApplication.translate("KodosBA", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setText(QtGui.QApplication.translate("KodosBA", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setIconText(QtGui.QApplication.translate("KodosBA", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setText(QtGui.QApplication.translate("KodosBA", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setIconText(QtGui.QApplication.translate("KodosBA", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setText(QtGui.QApplication.translate("KodosBA", "&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setIconText(QtGui.QApplication.translate("KodosBA", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setText(QtGui.QApplication.translate("KodosBA", "C&opy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setIconText(QtGui.QApplication.translate("KodosBA", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setText(QtGui.QApplication.translate("KodosBA", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setIconText(QtGui.QApplication.translate("KodosBA", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.examineAction.setText(QtGui.QApplication.translate("KodosBA", "E&xamine Regex", None, QtGui.QApplication.UnicodeUTF8))
        self.examineAction.setIconText(QtGui.QApplication.translate("KodosBA", "Examine Regex for Match", None, QtGui.QApplication.UnicodeUTF8))
        self.examineAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.helpContentsAction.setText(QtGui.QApplication.translate("KodosBA", "&Contents...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpContentsAction.setIconText(QtGui.QApplication.translate("KodosBA", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setText(QtGui.QApplication.translate("KodosBA", "&Index...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setIconText(QtGui.QApplication.translate("KodosBA", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAboutAction.setText(QtGui.QApplication.translate("KodosBA", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAboutAction.setIconText(QtGui.QApplication.translate("KodosBA", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.regexChangedAction.setText(QtGui.QApplication.translate("KodosBA", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.regexChangedAction.setIconText(QtGui.QApplication.translate("KodosBA", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.editPauseAction.setText(QtGui.QApplication.translate("KodosBA", "Pause Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.editPauseAction.setIconText(QtGui.QApplication.translate("KodosBA", "Pause Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.editPauseAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.editPreferencesAction.setText(QtGui.QApplication.translate("KodosBA", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.editPreferencesAction.setIconText(QtGui.QApplication.translate("KodosBA", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.helpHelpAction.setText(QtGui.QApplication.translate("KodosBA", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpHelpAction.setIconText(QtGui.QApplication.translate("KodosBA", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpHelpAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+/", None, QtGui.QApplication.UnicodeUTF8))
        self.helpPythonHelpAction.setText(QtGui.QApplication.translate("KodosBA", "&Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpPythonHelpAction.setIconText(QtGui.QApplication.translate("KodosBA", "Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexReferenceAction.setText(QtGui.QApplication.translate("KodosBA", "&Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexReferenceAction.setIconText(QtGui.QApplication.translate("KodosBA", "Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexReferenceAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.helpVisitWebsiteAction.setText(QtGui.QApplication.translate("KodosBA", "&Visit Kodos Website", None, QtGui.QApplication.UnicodeUTF8))
        self.helpVisitWebsiteAction.setIconText(QtGui.QApplication.translate("KodosBA", "&Visit Kodos Website", None, QtGui.QApplication.UnicodeUTF8))
        self.helpCheckForUpdateAction.setText(QtGui.QApplication.translate("KodosBA", "&Check for Kodos Update", None, QtGui.QApplication.UnicodeUTF8))
        self.helpCheckForUpdateAction.setIconText(QtGui.QApplication.translate("KodosBA", "Check for Kodos Update", None, QtGui.QApplication.UnicodeUTF8))
        self.helpReportBugAction.setText(QtGui.QApplication.translate("KodosBA", "Report a &Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.helpReportBugAction.setIconText(QtGui.QApplication.translate("KodosBA", "Report a Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.fileImportFileAction.setText(QtGui.QApplication.translate("KodosBA", "Import &File", None, QtGui.QApplication.UnicodeUTF8))
        self.fileImportFileAction.setIconText(QtGui.QApplication.translate("KodosBA", "Import File", None, QtGui.QApplication.UnicodeUTF8))
        self.fileImportURLAction.setText(QtGui.QApplication.translate("KodosBA", "Import &URL", None, QtGui.QApplication.UnicodeUTF8))
        self.fileImportURLAction.setIconText(QtGui.QApplication.translate("KodosBA", "Import URL", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexLibAction.setText(QtGui.QApplication.translate("KodosBA", "Regex &Library", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexLibAction.setIconText(QtGui.QApplication.translate("KodosBA", "Regex Library", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexLibAction.setToolTip(QtGui.QApplication.translate("KodosBA", "Open the Regex Library", None, QtGui.QApplication.UnicodeUTF8))
        self.helpRegexLibAction.setShortcut(QtGui.QApplication.translate("KodosBA", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.FileRevertAction.setText(QtGui.QApplication.translate("KodosBA", "&Revert Kodos File", None, QtGui.QApplication.UnicodeUTF8))
        self.FileRevertAction.setIconText(QtGui.QApplication.translate("KodosBA", "Revert Kodos File", None, QtGui.QApplication.UnicodeUTF8))


class KodosBA(QtGui.QMainWindow, Ui_KodosBA):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

