# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prefsBA.ui'
#
# Created: Wed Jan 13 13:46:58 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PrefsBA(object):
    def setupUi(self, PrefsBA):
        PrefsBA.setObjectName("PrefsBA")
        PrefsBA.resize(540, 257)
        PrefsBA.setSizeGripEnabled(False)
        self.layout5 = QtGui.QWidget(PrefsBA)
        self.layout5.setGeometry(QtCore.QRect(11, 6, 519, 246))
        self.layout5.setObjectName("layout5")
        self.vboxlayout = QtGui.QVBoxLayout(self.layout5)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.TextLabel2 = QtGui.QLabel(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2.sizePolicy().hasHeightForWidth())
        self.TextLabel2.setSizePolicy(sizePolicy)
        self.TextLabel2.setWordWrap(False)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridlayout.addWidget(self.TextLabel2, 1, 0, 1, 1)
        self.browserButton = QtGui.QPushButton(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browserButton.sizePolicy().hasHeightForWidth())
        self.browserButton.setSizePolicy(sizePolicy)
        self.browserButton.setObjectName("browserButton")
        self.gridlayout.addWidget(self.browserButton, 0, 3, 1, 1)
        self.browserEdit = QtGui.QLineEdit(self.layout5)
        self.browserEdit.setObjectName("browserEdit")
        self.gridlayout.addWidget(self.browserEdit, 0, 1, 1, 2)
        self.fontButtonMatch = QtGui.QPushButton(self.layout5)
        self.fontButtonMatch.setObjectName("fontButtonMatch")
        self.gridlayout.addWidget(self.fontButtonMatch, 2, 1, 2, 3)
        self.textLabel1 = QtGui.QLabel(self.layout5)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 2, 0, 1, 1)
        self.fontButton = QtGui.QPushButton(self.layout5)
        self.fontButton.setObjectName("fontButton")
        self.gridlayout.addWidget(self.fontButton, 1, 1, 1, 3)
        self.emailServerEdit = QtGui.QLineEdit(self.layout5)
        self.emailServerEdit.setObjectName("emailServerEdit")
        self.gridlayout.addWidget(self.emailServerEdit, 4, 1, 1, 3)
        self.TextLabel1_2Emaii = QtGui.QLabel(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1_2Emaii.sizePolicy().hasHeightForWidth())
        self.TextLabel1_2Emaii.setSizePolicy(sizePolicy)
        self.TextLabel1_2Emaii.setWordWrap(False)
        self.TextLabel1_2Emaii.setObjectName("TextLabel1_2Emaii")
        self.gridlayout.addWidget(self.TextLabel1_2Emaii, 3, 0, 2, 1)
        self.TextLabel1_2 = QtGui.QLabel(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1_2.sizePolicy().hasHeightForWidth())
        self.TextLabel1_2.setSizePolicy(sizePolicy)
        self.TextLabel1_2.setWordWrap(False)
        self.TextLabel1_2.setObjectName("TextLabel1_2")
        self.gridlayout.addWidget(self.TextLabel1_2, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(380, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 5, 2, 1, 2)
        self.recentFilesSpinBox = QtGui.QSpinBox(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentFilesSpinBox.sizePolicy().hasHeightForWidth())
        self.recentFilesSpinBox.setSizePolicy(sizePolicy)
        self.recentFilesSpinBox.setMaximum(25)
        self.recentFilesSpinBox.setProperty("value", QtCore.QVariant(5))
        self.recentFilesSpinBox.setObjectName("recentFilesSpinBox")
        self.gridlayout.addWidget(self.recentFilesSpinBox, 5, 1, 1, 1)
        self.TextLabel1 = QtGui.QLabel(self.layout5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1.sizePolicy().hasHeightForWidth())
        self.TextLabel1.setSizePolicy(sizePolicy)
        self.TextLabel1.setWordWrap(False)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridlayout.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.buttonHelp = QtGui.QPushButton(self.layout5)
        self.buttonHelp.setAutoDefault(True)
        self.buttonHelp.setObjectName("buttonHelp")
        self.hboxlayout.addWidget(self.buttonHelp)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.buttonApply = QtGui.QPushButton(self.layout5)
        self.buttonApply.setAutoDefault(True)
        self.buttonApply.setObjectName("buttonApply")
        self.hboxlayout.addWidget(self.buttonApply)
        self.buttonOk = QtGui.QPushButton(self.layout5)
        self.buttonOk.setAutoDefault(True)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.hboxlayout.addWidget(self.buttonOk)
        self.buttonCancel = QtGui.QPushButton(self.layout5)
        self.buttonCancel.setAutoDefault(True)
        self.buttonCancel.setObjectName("buttonCancel")
        self.hboxlayout.addWidget(self.buttonCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(PrefsBA)
        QtCore.QObject.connect(self.buttonOk, QtCore.SIGNAL("clicked()"), PrefsBA.accept)
        QtCore.QObject.connect(self.buttonCancel, QtCore.SIGNAL("clicked()"), PrefsBA.reject)
        QtCore.QObject.connect(self.browserButton, QtCore.SIGNAL("pressed()"), PrefsBA.browser_slot)
        QtCore.QObject.connect(self.fontButton, QtCore.SIGNAL("pressed()"), PrefsBA.font_slot)
        QtCore.QObject.connect(self.buttonHelp, QtCore.SIGNAL("pressed()"), PrefsBA.help_slot)
        QtCore.QObject.connect(self.buttonApply, QtCore.SIGNAL("pressed()"), PrefsBA.apply_slot)
        QtCore.QObject.connect(self.fontButtonMatch, QtCore.SIGNAL("pressed()"), PrefsBA.match_font_slot)
        QtCore.QMetaObject.connectSlotsByName(PrefsBA)
        PrefsBA.setTabOrder(self.browserEdit, self.browserButton)
        PrefsBA.setTabOrder(self.browserButton, self.fontButton)
        PrefsBA.setTabOrder(self.fontButton, self.emailServerEdit)
        PrefsBA.setTabOrder(self.emailServerEdit, self.recentFilesSpinBox)
        PrefsBA.setTabOrder(self.recentFilesSpinBox, self.buttonHelp)
        PrefsBA.setTabOrder(self.buttonHelp, self.buttonApply)
        PrefsBA.setTabOrder(self.buttonApply, self.buttonOk)
        PrefsBA.setTabOrder(self.buttonOk, self.buttonCancel)

    def retranslateUi(self, PrefsBA):
        PrefsBA.setWindowTitle(QtGui.QApplication.translate("PrefsBA", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel2.setText(QtGui.QApplication.translate("PrefsBA", "Editor Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.browserButton.setText(QtGui.QApplication.translate("PrefsBA", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("PrefsBA", "Match Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel1_2Emaii.setText(QtGui.QApplication.translate("PrefsBA", "Email Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel1_2.setText(QtGui.QApplication.translate("PrefsBA", "Recent Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel1.setText(QtGui.QApplication.translate("PrefsBA", "Web Browser:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonHelp.setText(QtGui.QApplication.translate("PrefsBA", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonApply.setText(QtGui.QApplication.translate("PrefsBA", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOk.setText(QtGui.QApplication.translate("PrefsBA", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setText(QtGui.QApplication.translate("PrefsBA", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

