# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'referenceBA.ui'
#
# Created: Wed Jan 13 14:35:23 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ReferenceBA(object):
    def setupUi(self, ReferenceBA):
        ReferenceBA.setObjectName("ReferenceBA")
        ReferenceBA.resize(600, 605)
        self.widget = QtGui.QWidget(ReferenceBA)
        self.widget.setObjectName("widget")
        self.gridlayout = QtGui.QGridLayout(self.widget)
        self.gridlayout.setObjectName("gridlayout")
        self.referenceListView = QtGui.QTreeWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceListView.sizePolicy().hasHeightForWidth())
        self.referenceListView.setSizePolicy(sizePolicy)
        self.referenceListView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.referenceListView.setFrameShadow(QtGui.QFrame.Sunken)
        self.referenceListView.setRootIsDecorated(False)
        self.referenceListView.setAllColumnsShowFocus(True)
        self.referenceListView.setObjectName("referenceListView")
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        item_0 = QtGui.QTreeWidgetItem(self.referenceListView)
        self.gridlayout.addWidget(self.referenceListView, 0, 0, 1, 1)
        ReferenceBA.setCentralWidget(self.widget)
        self.toolBar = QtGui.QToolBar(ReferenceBA)
        self.toolBar.setProperty("label", QtCore.QVariant(QtGui.QApplication.translate("ReferenceBA", "Tools", None, QtGui.QApplication.UnicodeUTF8)))
        self.toolBar.setObjectName("toolBar")
        ReferenceBA.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.MenuBar = QtGui.QMenuBar(ReferenceBA)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.MenuBar.setObjectName("MenuBar")
        self.fileMenu = QtGui.QMenu(self.MenuBar)
        self.fileMenu.setObjectName("fileMenu")
        self.editMenu = QtGui.QMenu(self.MenuBar)
        self.editMenu.setObjectName("editMenu")
        self.helpMenu = QtGui.QMenu(self.MenuBar)
        self.helpMenu.setObjectName("helpMenu")
        ReferenceBA.setMenuBar(self.MenuBar)
        self.fileNewAction = QtGui.QAction(ReferenceBA)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image1"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileNewAction.setIcon(icon)
        self.fileNewAction.setProperty("name", QtCore.QVariant("fileNewAction"))
        self.fileNewAction.setObjectName("fileNewAction")
        self.fileOpenAction = QtGui.QAction(ReferenceBA)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image2"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon1)
        self.fileOpenAction.setProperty("name", QtCore.QVariant("fileOpenAction"))
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileSaveAction = QtGui.QAction(ReferenceBA)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image3"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSaveAction.setIcon(icon2)
        self.fileSaveAction.setProperty("name", QtCore.QVariant("fileSaveAction"))
        self.fileSaveAction.setObjectName("fileSaveAction")
        self.fileSaveAsAction = QtGui.QAction(ReferenceBA)
        self.fileSaveAsAction.setProperty("name", QtCore.QVariant("fileSaveAsAction"))
        self.fileSaveAsAction.setObjectName("fileSaveAsAction")
        self.filePrintAction = QtGui.QAction(ReferenceBA)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image4"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePrintAction.setIcon(icon3)
        self.filePrintAction.setProperty("name", QtCore.QVariant("filePrintAction"))
        self.filePrintAction.setObjectName("filePrintAction")
        self.fileExitAction = QtGui.QAction(ReferenceBA)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image5"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileExitAction.setIcon(icon4)
        self.fileExitAction.setProperty("name", QtCore.QVariant("fileExitAction"))
        self.fileExitAction.setObjectName("fileExitAction")
        self.editUndoAction = QtGui.QAction(ReferenceBA)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image6"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndoAction.setIcon(icon5)
        self.editUndoAction.setProperty("name", QtCore.QVariant("editUndoAction"))
        self.editUndoAction.setObjectName("editUndoAction")
        self.editRedoAction = QtGui.QAction(ReferenceBA)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image7"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRedoAction.setIcon(icon6)
        self.editRedoAction.setProperty("name", QtCore.QVariant("editRedoAction"))
        self.editRedoAction.setObjectName("editRedoAction")
        self.editCutAction = QtGui.QAction(ReferenceBA)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("image8"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon7)
        self.editCutAction.setProperty("name", QtCore.QVariant("editCutAction"))
        self.editCutAction.setObjectName("editCutAction")
        self.editCopyAction = QtGui.QAction(ReferenceBA)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("image9"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCopyAction.setIcon(icon8)
        self.editCopyAction.setProperty("name", QtCore.QVariant("editCopyAction"))
        self.editCopyAction.setObjectName("editCopyAction")
        self.editPasteAction = QtGui.QAction(ReferenceBA)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("image10"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPasteAction.setIcon(icon9)
        self.editPasteAction.setProperty("name", QtCore.QVariant("editPasteAction"))
        self.editPasteAction.setObjectName("editPasteAction")
        self.editFindAction = QtGui.QAction(ReferenceBA)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("image11"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFindAction.setIcon(icon10)
        self.editFindAction.setProperty("name", QtCore.QVariant("editFindAction"))
        self.editFindAction.setObjectName("editFindAction")
        self.helpContentsAction = QtGui.QAction(ReferenceBA)
        self.helpContentsAction.setProperty("name", QtCore.QVariant("helpContentsAction"))
        self.helpContentsAction.setObjectName("helpContentsAction")
        self.helpIndexAction = QtGui.QAction(ReferenceBA)
        self.helpIndexAction.setProperty("name", QtCore.QVariant("helpIndexAction"))
        self.helpIndexAction.setObjectName("helpIndexAction")
        self.helpAboutAction = QtGui.QAction(ReferenceBA)
        self.helpAboutAction.setProperty("name", QtCore.QVariant("helpAboutAction"))
        self.helpAboutAction.setObjectName("helpAboutAction")
        self.helpAction = QtGui.QAction(ReferenceBA)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("image12"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpAction.setIcon(icon11)
        self.helpAction.setProperty("name", QtCore.QVariant("helpAction"))
        self.helpAction.setObjectName("helpAction")
        self.helpPythonAction = QtGui.QAction(ReferenceBA)
        self.helpPythonAction.setProperty("name", QtCore.QVariant("helpPythonAction"))
        self.helpPythonAction.setObjectName("helpPythonAction")
        self.toolBar.addAction(self.fileExitAction)
        self.toolBar.addAction(self.editPasteAction)
        self.toolBar.addAction(self.helpContentsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.editMenu.addAction(self.editPasteAction)
        self.editMenu.addSeparator()
        self.helpMenu.addAction(self.helpAction)
        self.helpMenu.addAction(self.helpPythonAction)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.editMenu.menuAction())
        self.MenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(ReferenceBA)
        QtCore.QObject.connect(self.fileExitAction, QtCore.SIGNAL("activated()"), ReferenceBA.close)
        QtCore.QObject.connect(self.editPasteAction, QtCore.SIGNAL("activated()"), ReferenceBA.editPaste)
        QtCore.QObject.connect(self.helpAction, QtCore.SIGNAL("activated()"), ReferenceBA.help_slot)
        QtCore.QObject.connect(self.referenceListView, QtCore.SIGNAL("doubleClicked(QListViewItem*)"), ReferenceBA.editPaste)
        QtCore.QObject.connect(self.helpPythonAction, QtCore.SIGNAL("activated()"), ReferenceBA.help_python_slot)
        QtCore.QMetaObject.connectSlotsByName(ReferenceBA)

    def retranslateUi(self, ReferenceBA):
        ReferenceBA.setWindowTitle(QtGui.QApplication.translate("ReferenceBA", "Kodos - Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.headerItem().setText(0, QtGui.QApplication.translate("ReferenceBA", "Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.headerItem().setText(1, QtGui.QApplication.translate("ReferenceBA", "Definition", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.referenceListView.isSortingEnabled()
        self.referenceListView.setSortingEnabled(False)
        self.referenceListView.topLevelItem(0).setText(0, QtGui.QApplication.translate("ReferenceBA", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(0).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches start of string", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(1).setText(0, QtGui.QApplication.translate("ReferenceBA", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(1).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches 0 or 1 repetition of preceeding RE", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(2).setText(0, QtGui.QApplication.translate("ReferenceBA", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(2).setText(1, QtGui.QApplication.translate("ReferenceBA", "Non-greedy ?", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(3).setText(0, QtGui.QApplication.translate("ReferenceBA", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(3).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any character", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(4).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?<=...)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(4).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches if the current position in the string is preceded by a match for ... that ends at the current position. This is called a positive lookbehind assertion.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(5).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?<!...)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(5).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches if the current position in the string is not preceded by a match for .... This is called a negative lookbehind assertion.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(6).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?=...) ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(6).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches if ... matches next, but doesn\'t consume any of the string. This is called a lookahead assertion.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(7).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?:)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(7).setText(1, QtGui.QApplication.translate("ReferenceBA", "Non-capturing Parenthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(8).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?!...)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(8).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches if ... doesn\'t match next. This is a negative lookahead assertion", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(9).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?#...) ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(9).setText(1, QtGui.QApplication.translate("ReferenceBA", "A comment; the contents of the parentheses are simply ignored.  ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(10).setText(0, QtGui.QApplication.translate("ReferenceBA", "()", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(10).setText(1, QtGui.QApplication.translate("ReferenceBA", "Capturing Parenthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(11).setText(0, QtGui.QApplication.translate("ReferenceBA", "[]", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(11).setText(1, QtGui.QApplication.translate("ReferenceBA", "Character class", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(12).setText(0, QtGui.QApplication.translate("ReferenceBA", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(12).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches the end of the string", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(13).setText(0, QtGui.QApplication.translate("ReferenceBA", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(13).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches 0 or more repetition of preceeding RE", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(14).setText(0, QtGui.QApplication.translate("ReferenceBA", "*?", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(14).setText(1, QtGui.QApplication.translate("ReferenceBA", "Non-greedy *", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(15).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\\\", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(15).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches a literal backslash", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(16).setText(0, QtGui.QApplication.translate("ReferenceBA", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(16).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches 1 or more repetition of preceeding RE", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(17).setText(0, QtGui.QApplication.translate("ReferenceBA", "+?", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(17).setText(1, QtGui.QApplication.translate("ReferenceBA", "Non-greedy +", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(18).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\A", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(18).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches only at the start of the string", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(19).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\b", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(19).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches the empty string, but only at the beginning or end of a word", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(20).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\B", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(20).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches the empty string, but only when it is not at the beginning or end of a  word", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(21).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\d", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(21).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any decimal digit", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(22).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\D", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(22).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any non-digit character", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(23).setText(0, QtGui.QApplication.translate("ReferenceBA", "{m,n}", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(23).setText(1, QtGui.QApplication.translate("ReferenceBA", "match from m to n repetitions of the preceding RE, attempting to match as many repetitions as possible. ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(24).setText(0, QtGui.QApplication.translate("ReferenceBA", "{m,n}?", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(24).setText(1, QtGui.QApplication.translate("ReferenceBA", "match from m to n repetitions of the preceding RE, attempting to match as few repetitions as possible. ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(25).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\number ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(25).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches the contents of the group of the same number. Groups are numbered starting from 1.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(26).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?P<name>...)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(26).setText(1, QtGui.QApplication.translate("ReferenceBA", "Similar to regular parentheses, but the substring matched by the group is accessible via the symbolic group name name.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(27).setText(0, QtGui.QApplication.translate("ReferenceBA", "(?P=name)", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(27).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches whatever text was matched by the earlier group named name. ", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(28).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\s", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(28).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any whitespace character", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(29).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\S", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(29).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any non-whitespace character", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(30).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\w", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(30).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any word", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(31).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\W", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(31).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches any non-word", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(32).setText(0, QtGui.QApplication.translate("ReferenceBA", "\\z", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.topLevelItem(32).setText(1, QtGui.QApplication.translate("ReferenceBA", "Matches only at the end of the string", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceListView.setSortingEnabled(__sortingEnabled)
        self.fileMenu.setTitle(QtGui.QApplication.translate("ReferenceBA", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("ReferenceBA", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("ReferenceBA", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setText(QtGui.QApplication.translate("ReferenceBA", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setText(QtGui.QApplication.translate("ReferenceBA", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setText(QtGui.QApplication.translate("ReferenceBA", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setText(QtGui.QApplication.translate("ReferenceBA", "C&opy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setToolTip(QtGui.QApplication.translate("ReferenceBA", "Paste selection into Kodos", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Find...", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setShortcut(QtGui.QApplication.translate("ReferenceBA", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.helpContentsAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Contents...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpContentsAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Index...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAboutAction.setText(QtGui.QApplication.translate("ReferenceBA", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAboutAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpPythonAction.setText(QtGui.QApplication.translate("ReferenceBA", "&Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpPythonAction.setIconText(QtGui.QApplication.translate("ReferenceBA", "Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))

